export const HYDRATE = "HYDRATE";
export const DELETE_VALUE = "DELETE_VALUE";
export const VALUE_CHANGED = "VALUE_CHANGED";

//Auth actions
export const VALIDATE_EMAIL = "VALIDATE_EMAIL";
export const VALIDATE_EMAIL_FAILED = "VALIDATE_EMAIL_FAILED";
export const VALIDATE_EMAIL_SUCCEEDED = "VALIDATE_EMAIL_SUCCEEDED";

export const USER_REGISTRATION = "USER_REGISTRATION";
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";
export const USER_REGISTRATION_SUCCEEDED = "USER_REGISTRATION_SUCCEEDED";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
